---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 30s
  ref:
    tag: v1.0.0
  url: ssh://git@github.com/maratkaz/k8s-flux.git
