---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 30s
  ref:
    tag: v5.0.0
  secretRef:
    name: flux-system
  url: ssh://git@github.com/maratkaz/k8s-flux
